# Generated by Django 5.1.3 on 2024-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basketitem",
            old_name="cart",
            new_name="basket",
        ),
        migrations.AlterUniqueTogether(
            name="basketitem",
            unique_together={("basket", "product")},
        ),
    ]
